#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  gem 'openstax_kitchen', ENV['USE_LOCAL_KITCHEN'] ? { path: '/code/kitchen' } : '2.0.0'
  gem 'slop', '4.8.2'
  gem 'byebug'
end

recipe = Kitchen::BookRecipe.new(book_short_name: :uphysics) do |doc|
  include Kitchen::Directions

  book = doc.book

  book.search('cnx-pi').trash

  BakePreface.v1(book: book)
  BakeUnitTitle.v1(book: book)

  book.chapters.each do |chapter|
    BakeChapterGlossary.v1(chapter: chapter, metadata_source: book.metadata)
    BakeChapterKeyEquations.v1(chapter: chapter, metadata_source: book.metadata)
    #BakeChapterKeyConcepts.v1(chapter: chapter, metadata_source: book.metadata)
    #BakeChapterReviewConceptualQuestions.v1(chapter: chapter, metadata_source: book.metadata)
  end

  #BakeExercises.v2(book: book)
  BakeExercises.v1(book: book, class_name: 'section.review-conceptual-questions', bake_eob: false)
  BakeExercises.v1(book: book, class_name: 'section.review-problems', bake_eob: false)
  BakeExercises.v1(book: book, class_name: 'section.review-additional-problems', bake_eob: false)
  BakeExercises.v1(book: book, class_name: 'section.review-challenge', bake_eob: false)
  BakeExercises.eob(book: book, class_names:
    {
      'review_conceptual_questions':
        {
          classname: '.review-conceptual-questions',
          decimal: false,
          sectional: false
        },
      'review_problems':
        {
          classname: '.review-problems',
          decimal: false,
          sectional: false
        },
      'review_additional_problems':
        {
          classname: '.review-additional-problems',
          decimal: false,
          sectional: false
        },
      'review_challenge_problems':
        {
          classname: '.review-challenge-problems',
          decimal: false,
          sectional: false
        },
    })

  BakeChapterIntroductions.v1(book: book)
  BakeChapterTitle.v1(book: book)

  book.chapters.each do |chapter|
    BakePageAbstracts.v1(chapter: chapter)

    chapter.tables('$:not(.unnumbered)').each do |table|
      BakeNumberedTable.v1(table: table,
                           number: "#{chapter.count_in(:book)}.#{table.count_in(:chapter)}")
    end

    chapter.examples.each do |example|
      BakeExample.v1(example: example,
                     number: "#{chapter.count_in(:book)}.#{example.count_in(:chapter)}",
                     title_tag: 'h3')
    end

    chapter.pages('$:not(.introduction)').each do |page|
      page.search("div[data-type='description']").each(&:trash)
      page.add_class('chapter-content-module')

      title = page.search("div[data-type='document-title']").first
      title.name = 'h2'
      title.replace_children(with:
        <<~HTML
          <span class="os-number">#{chapter.count_in(:book)}.#{page.count_in(:chapter)}</span>
          <span class="os-divider"> </span>
          <span data-type="" itemprop="" class="os-text">#{title.text}</span>
        HTML
      )
    end

    chapter.figures.each do |figure|
      BakeFigure.v1(figure: figure,
                    number: "#{chapter.count_in(:book)}.#{figure.count_in(:chapter)}")
    end
  end

  BakeUnnumberedTables.v1(book: book)
  #BakeNotes.v1(book: book)
  BakeMathInParagraph.v1(book: book)
  BakeIndex.v1(book: book)
  BakeCompositePages.v1(book: book)

  BakeToc.v1(book: book)
  BakeLinkPlaceholders.v1(book: book)
end

normalize = Kitchen::BookRecipe.new(book_short_name: :u_physics) do |doc|
  include Kitchen::Directions

  book = doc.book

  # remove copy_XXX from places that don't have it
  book.search('[data-type="solution"]').each do |solution|
    solution[:id] = solution[:id].gsub(/_copy_(\d+)$/, '')
  end
  book.search('.os-solution-container').search('p').each do |p|
    p[:id] = p[:id].gsub(/_copy_(\d+)$/, '') if p[:id]
  end

  # remove w3 from toc
  #book.search('nav#toc').first.search()
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: [recipe, normalize],
  output_file: opts[:output]
)
